variables: 
    project: shared-resources
stages: 
    - 
    displayName: Validate
    jobs: 
        - 
        template: pipelines/jobs/terraform/validate.yml
    stage: validate
    variables: 
        - 
        group: shared
    - 
    condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
    displayName: "Plan for development"
    jobs: 
        - 
        parameters: 
            workspace: dev
        template: pipelines/jobs/terraform/plan.yml
    stage: plan_dev
    variables: 
        - 
        group: shared
    - 
    displayName: "Apply for development"
    jobs: 
        - 
        parameters: 
            project: "${{ variables.project }}"
            workspace: dev
        template: pipelines/jobs/terraform/apply.yml
    stage: apply_dev
    variables: 
        - 
        group: shared

