stages:
  - stage: plan_dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Plan for development
    variables:
        - group: shared
    
    jobs:
        - template: pipelines/jobs/terraform/plan.yml
          parameters:
              workspace: dev
    
  - stage: apply_dev
    displayName: Apply for development
    variables:
        - group: shared
    
    jobs:
        - template: pipelines/jobs/terraform/apply.yml
          parameters:
              project: ${{ variables.project }}
              workspace: dev
