parameters:
  project: ""
  workspace: ""

jobs:
  - deployment: apply_terraform
    displayName: Apply Terraform
    environment: ${{ parameters.project }}-${{ parameters.workspace }}
    pool: terraform_aci_laptop
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../../steps/terraform/install.yml

            - bash: |
                $TERRAFORM_BINARY apply \
                  -input=false \
                  -auto-approve 
              displayName: Apply Terraform plan
              workingDirectory: $(Pipeline.Workspace)/terraform
