parameters:
  project: ""
  workspace: ""

jobs:
  - job: apply_terraform
    displayName: Apply Terraform
    pool: terraform_aci_laptop
    variables:
      - group: shared
    steps:
      - template: ../../steps/terraform/install.yml
      - template: ../../steps/terraform/init.yml

      - bash: |
          $TERRAFORM_BINARY apply \
            -input=false \
            -auto-approve 
        displayName: Apply Terraform plan
        workingDirectory: "$(Build.SourcesDirectory)/terraform"
        env:
          TF_VAR_apic_password: $(apic_password)
