parameters:
  workspace: ""
  tf_vars: {}

jobs:
  - job: plan_terraform
    displayName: Create Terraform plan
    pool: terraform_aci_laptop
    variables:
        - group: shared
    steps:
      - template: ../../steps/terraform/install.yml
      - template: ../../steps/terraform/init.yml

      - bash: |
          $TERRAFORM_BINARY plan \
            -out=${{ parameters.workspace }}.tfplan \
            -input=false \
            -detailed-exitcode \
            -no-color 
        displayName: Create Terraform plan
        workingDirectory: "$(Build.SourcesDirectory)/terraform"
        env:
            TF_VAR_apic_password: $(apic_password)