jobs:
  - job: validate_terraform
    displayName: Validate Terraform
    pool: azure_devops_terraform_aci
    steps:
      - template: ../../steps/terraform/install.yml

      - bash: |
          # Validate Terraform scripts
          $TERRAFORM_BINARY init -backend=false
          $TERRAFORM_BINARY validate
        displayName: Validate Terraform scripts
        workingDirectory: "$(Build.SourcesDirectory)/terraform"