jobs:
  - job: validate_terraform
    displayName: Validate Terraform
    pool: terraform_aci_laptop
    steps:
      - template: ../../steps/terraform/install.yml

      - bash: |
          # Validate Terraform scripts
          $TERRAFORM_BINARY init -backend=false
          $TERRAFORM_BINARY validate
        displayName: Validate Terraform scripts
        workingDirectory: "$(Build.SourcesDirectory)/terraform"